# Generated by Django 4.2.13 on 2024-08-28 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='my_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
    ]
