# Generated by Django 4.2.13 on 2024-08-28 19:50

from django.db import migrations
import random
from django.conf import settings

def populate_random_user(apps, schema_editor):
    # Get the models
    Country = apps.get_model('exercise_1', 'Country')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    # Get all users and countries
    users = list(User.objects.all())
    countries = Country.objects.filter(my_user__isnull=True)

    # Assign a random user to each country
    for country in countries:
        if users:
            country.my_user = random.choice(users)
            country.save()



class Migration(migrations.Migration):

    dependencies = [
        ('exercise_1', '0002_country_my_user'),
    ]

    operations = [
        migrations.RunPython(populate_random_user),
    ]
