# Generated by Django 4.2.13 on 2024-07-13 09:57
import random
from django.db import migrations, models


class Migration(migrations.Migration):
    def populate_random_user(apps, schema_editor):
        User = apps.get_model('exercise_1', 'User')
        Country = apps.get_model('exercise_1', 'Country')
        for country in Country.objects.all():
            random_user_name = ''.join((random.choice('saikiran') for i in range(5)))
            user = User.objects.create(Email = random_user_name)
            user.save()
            country.my_user = user
            country.save()
    def undo_populate_random_user(apps, schema_editor):
        User = apps.get_model('exercise_1', 'User')
        Country = apps.get_model('exercise_1', 'Country')
        for country in Country.objects.all():
            if country.my_user:
                country.my_user.delete()
            country.my_user = None
            country.save()

    dependencies = [
        ('exercise_1', '0002_user_country_my_user'),
    ]

    operations = [
        # addding Random user to Country 
        migrations.RunPython(populate_random_user,undo_populate_random_user),

        # remove null from the Country mu_user forignkey
        migrations.AlterField(
            model_name="Country",
            name="my_user",
            field=models.ForeignKey(to='exercise_1.User', on_delete=models.CASCADE),
        ),
        
    ]
