# Generated by Django 4.2.13 on 2024-08-28 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_1', '0003_populate_random_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
    ]
