# Generated by Django 4.2.13 on 2024-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_1', '0004_alter_country_my_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='phone_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='gst_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'city_code')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'name')},
        ),
    ]
